AULA 03 - NumPy Array

Principal módulo para operações numéricas, tanto que virou padrão na comunidade, principalmente pela sua representação de matrizes, chamadas de NumPy arrays. 

In [8]:
print([1, 2, 3] * 2)
print([1, 2, 3] + [1, 2, 3])

notas = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(len(notas))

notas_a = str(notas)
print(notas_a)
print(type(notas_a))



[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]
3
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'str'>


In [11]:
import numpy as np
matriz1d = np.array([1, 2, 3,])
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz1d * 2)
print(matriz1d + matriz1d)
print(matriz2d.shape)


[2 4 6]
[2 4 6]
(3, 3)


In [12]:
print([1, 2, 3] + [4, 5, 6])
print(np.array([1, 2, 3]) + np.array([4, 5, 6]))

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [13]:
print([1, 2, 3] * 3)
print(np.array([1, 2, 3]) * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [15]:
import numpy as np

matriz1d = np.array([1, 2, 3])
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(matriz1d.ndim) # 1
print(matriz2d.ndim) # 2
print(matriz3d.ndim) # 3
print(matriz1d.shape) # (3, )

1
2
3
(3,)


Como em Matemática, as matrizes em NumPy realizam operações matemáticas básicas, como soma, subtração, multiplicação e multiplicação por número. Confira abaixo alguns exemplos das operações descritas anteriormente:



In [19]:
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2d2 = np.array([[20, 12, 10], [16, 55, 45], [33, 27, 18]])
print(matriz2d + matriz2d2)
print()
print(matriz2d2 - matriz2d)
print()
print(matriz2d * 2)

[[21 14 13]
 [20 60 51]
 [40 35 27]]

[[19 10  7]
 [12 50 39]
 [26 19  9]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
