Oficina Aula 3

analisasse as visualizações diárias de stories da última semana para uma lista de pessoas.

In [1]:
import numpy as np


In [2]:
import numpy.ma as ma

In [22]:
v_stories = np.array([[187, 120, 88, 70, 130, 168, 213],
                      [0, 0, 42, 0, 0, 55, 77],
                      [91, 0, 61, 0, 71, 121, 271],
                      [0, 0, 0, 0, 187, 0, 0],
                      [42, 23, 34, 0, 39, 29, 36]])
print(v_stories.shape, '| O primeiro número são QTD de pessoas e outro dias da semana.\n'.upper())

pessoas = ['Raquel', 'Lucas', ' Daniel', 'Natalia', 'Anderson']
print(pessoas, '| Esses são os usuários que fizeram as visualizações.\n'.upper())

dias = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado']
print(dias, '| Dias da semana a serem pesquisados.\n'.upper())

(5, 7) | O PRIMEIRO NÚMERO SÃO QTD DE PESSOAS E OUTRO DIAS DA SEMANA.

['Raquel', 'Lucas', ' Daniel', 'Natalia', 'Anderson'] | ESSES SÃO OS USUÁRIOS QUE FIZERAM AS VISUALIZAÇÕES.

['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'] | DIAS DA SEMANA A SEREM PESQUISADOS.



Os dados estão organizados da seguinte forma: a primeira linha se refere aos stories da Raquel; a segunda, aos do Lucas; e assim por diante. Com relação às colunas, a primeira coluna são os stories do Domingo, em seguida, os stories da Segunda e assim por diante até a última coluna, que se refere ao Sábado.

 Qual a média de visualizações por dia de todas essas pessoas? 
 
 Qual o dia que teve mais visualizações de stories somadas? 
 
 Quem foi que teve o maior número de visualizações na última semana?

In [26]:
print(v_stories.mean(axis=0), '| Média de visualizações por dia de todas as pessoas em uma semana.\n')
print(v_stories.mean(axis=0).shape, '| Conferindo a matriz da média dos dias da semana.\n')

[ 64.   28.6  45.   14.   85.4  74.6 119.4] | Média de visualizações por dia de todas as pessoas em uma semana.

(7,) | Conferindo a matriza da média dos dias da semana.



In [27]:
v_media = v_stories.mean(axis=0)
print(v_media)

[ 64.   28.6  45.   14.   85.4  74.6 119.4]


In [35]:
v_soma = v_stories.sum(axis=0)
print(v_soma, '| Soma de visualizações em cada dia da semana.\n')

m_visualizacao = v_soma.max()
print(m_visualizacao, '| Número maior de visualizações foi no Sábado.\n')

[320 143 225  70 427 373 597] | Soma de visualizações em cada dia da semana.

597 | Número maior de visualizações foi no Sábado.



In [39]:
s_pessoas = v_stories.sum(axis=1)
print(s_pessoas, '| QTD. total de visualizações por pessoa.\n')

m_pessoa = s_pessoas.max()
print(m_pessoa, '| Pessoa que fez mais visualizações, Raquel.\n')

[976 174 615 187 203] | QTD. total de visualizações por pessoa.

976 | Pessoa que fez mais visualizações, Raquel.



In [46]:
v_stories_invalidos = np.array([[52, 68, 97, 55, -1, 98, -1],
                                [53, -1, 38, -1, -1, 72, 49],
                                [88, -1, 64, -1, 77, 130, 43],
                                [-1, 30, -1, -1, -1, 182, -1],
                                [41, 20, 33, -1, 37, 23, 7]])
print(v_stories_invalidos.shape, '| Conferindo a matriz.\n'.upper())



(5, 7) | CONFERINDO A MATRIZ.



In [42]:
from random import sample